### PR TITLE
Consider already existing images as successful pulls.

### LINKED ISSUE #2010: com.github.dockerjava.api.model.PullResponseItem#isPullSuccessIndicated fails to check for "Exists" status
com.github.dockerjava.api.model.PullResponseItem#isPullSuccessIndicated checks for several success states, but misses "Exists" and treats this status as a failure.

Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: Exists

If would be great if the success status codes could be a configurable list that the library user could append to.

### PR DESCRIPTION
**Pull request by n-g**
Fixes #2010 

Status can be found in upstream moby:
https://github.com/moby/moby/blob/f3f20c3a862ff90c7e7b0ee07dabe2176ed0a170/plugin/fetch_linux.go#L224

### CODE REVIEW

**Comment by n-g** [comment]
cc @eddumelendez

To add more context, this issue is causing a race condition in Testcontainers:

Testcontainers [skip](https://github.com/testcontainers/testcontainers-java/blob/main/core/src/main/java/org/testcontainers/images/RemoteDockerImage.java#L75) Docker pulls if an image is already cached.
However, two concurrent pulls for the same image would see no cached image. During the actual pull, one will encounter an "Already exists" which is (incorrectly) considered a failed pull.

File: docker-java-api/src/main/java/com/github/dockerjava/api/model/PullResponseItem.java [hunk 1]
```diff
@@ -34,7 +36,8 @@ public boolean isPullSuccessIndicated() {
                 getStatus().contains(IMAGE_UP_TO_DATE) ||
                 getStatus().contains(DOWNLOADED_NEWER_IMAGE) ||
                 getStatus().contains(LEGACY_REGISTRY) ||
-                getStatus().contains(DOWNLOADED_SWARM)
+                getStatus().contains(DOWNLOADED_SWARM)||
+                getStatus().contains(ALREADY_EXISTS)
```
Comment (eddumelendez) [inline docker-java-api/src/main/java/com/github/dockerjava/api/model/PullResponseItem.java:40]:
```suggestion
                getStatus().contains(DOWNLOADED_SWARM) ||
                getStatus().contains(ALREADY_EXISTS)
```

**Comment by eddumelendez** [comment]
Thanks for your contribution, @n-g !
