### PR TITLE
Use getters for objects

### LINKED ISSUE #539: Conflicting getter definitions for property "OomKillDisable"
I'm trying to create docker using docker-java api 3.0.0-RC4. Unfortunately I'm getting such error:

```
[ForkJoinPool-1-worker-1] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (com.fasterxml.jackson.databind.JsonMappingException) caught when processing request to {s}->__IP__: Conflicting getter definitions for property "OomKillDisable": com.github.dockerjava.api.model.HostConfig#getOomKillDisable(0 params) vs com.github.dockerjava.api.model.HostConfig#isOomKillDisable(0 params) (through reference chain: com.github.dockerjava.core.command.CreateContainerCmdImpl["HostConfig"])'`
```
I'm not sure if I'm doing sth wrong or it's a problem with dockerjava implementation.

Here is what Docker daemon writes to console:
```
Apr  8 16:17:35 b-worker docker[21567]: time="2016-04-08T16:17:35.533645803Z" level=error msg="Handler for POST /v1.22/containers/create returned error: unexpected EOF"
```

https://groups.google.com/d/msg/docker-java-dev/gfzC2AcsIso/GAIgJBjGAAAJ

### PR DESCRIPTION
**Pull request by KostyaSha**
Fixes #539

---
This change is [Reviewable](https://reviewable.io/reviews/docker-java/docker-java/540)

### CODE REVIEW

File: src/main/java/com/github/dockerjava/api/command/CreateContainerCmd.java [hunk 1]
```diff
@@ -159,16 +159,16 @@
...
     @CheckForNull
-    Boolean isPublishAllPorts();
+    Boolean getPublishAllPorts();
 
     @CheckForNull
-    Boolean isReadonlyRootfs();
+    Boolean getReadonlyRootfs();
 
     @CheckForNull
     Boolean isStdInOnce();
```
Comment (KostyaSha) [inline src/main/java/com/github/dockerjava/api/command/CreateContainerCmd.java]: this is also wrong...

Comment (marcuslinke) [inline src/main/java/com/github/dockerjava/api/command/CreateContainerCmd.java]: Do you fix this also then?

Comment (KostyaSha) [inline src/main/java/com/github/dockerjava/api/command/CreateContainerCmd.java]: I made docker-java generator for getters/setters/tostring/hash/equals and used them for only new fields. But then decided to generate all of them and fixed places that used to return boolean for Boolean...
