### PR TITLE
Fix ListSwarmNodesCmdImpl and Add basic tests

### LINKED ISSUE #1384: ListSwarmNodesCmdImpl calls wrong SwarmNodesFiltersBuilder methods
ListSwarmNodesCmdImpl's withMembershipFilter and withRoleFilter incorrectly calls withNames on the SwarmNodesFiltersBuilder.

### PR DESCRIPTION
**Pull request by klmntoth**
Fixes #1384

### CODE REVIEW

**Comment by bsideup** [comment]
@klmntoth please sync with the latest master to fix the CI

File: docker-java/src/test/java/com/github/dockerjava/cmd/swarm/ListSwarmNodesCmdExecIT.java [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+import com.github.dockerjava.api.model.SwarmSpec;
+import org.junit.Test;
+
+import java.util.Collections;
+import java.util.List;
+
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.is;
+
+public class ListSwarmNodesCmdExecIT extends SwarmCmdIT {
```
Comment (bsideup) [inline docker-java/src/test/java/com/github/dockerjava/cmd/swarm/ListSwarmNodesCmdExecIT.java:14]:
```suggestion
public class ListSwarmNodesCmdExecIT extends MultiNodeSwarmCmdIT {
```
